version: "3.8"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:alpine
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/config
    shm_size: "1gb"
    restart: unless-stopped
